# Test Pod for Ceph RBD
apiVersion: v1
kind: Pod
metadata:
  name: ceph-rbd-test-pod
  namespace: rook-ceph
spec:
  containers:
  - name: tester
    image: 192.168.40.248/library/busybox:1.36.1-1
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "=== Ceph RBD Write Test ===" > /data/test.txt
        echo "Current time: $(date)" >> /data/test.txt
        echo "Hostname: $(hostname)" >> /data/test.txt
        echo "Test completed successfully!" >> /data/test.txt
        echo "=== Reading test file ==="
        cat /data/test.txt
        echo ""
        echo "=== Testing write performance ==="
        dd if=/dev/zero of=/data/perf-test.dat bs=1M count=100 oflag=direct
        echo "Write test completed"
        echo ""
        echo "=== Testing read performance ==="
        dd if=/data/perf-test.dat of=/dev/null bs=1M count=100 iflag=direct
        echo "Read test completed"
        echo ""
        echo "=== File listing ==="
        ls -lh /data/
        echo ""
        echo "All tests completed!"
        sleep 3600
    volumeMounts:
    - name: ceph-rbd-vol
      mountPath: /data
  volumes:
  - name: ceph-rbd-vol
    persistentVolumeClaim:
      claimName: ceph-rbd-test-pvc
  restartPolicy: Never
---
# Test Pod for CephFS
apiVersion: v1
kind: Pod
metadata:
  name: cephfs-test-pod
  namespace: rook-ceph
spec:
  containers:
  - name: tester
    image: 192.168.40.248/library/busybox:1.36.1-1
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "=== CephFS Write Test ===" > /cephfs/test.txt
        echo "Current time: $(date)" >> /cephfs/test.txt
        echo "Hostname: $(hostname)" >> /cephfs/test.txt
        echo "Test completed successfully!" >> /cephfs/test.txt
        echo "=== Reading test file ==="
        cat /cephfs/test.txt
        echo ""
        echo "=== Testing write performance ==="
        dd if=/dev/zero of=/cephfs/perf-test.dat bs=1M count=100 oflag=direct
        echo "Write test completed"
        echo ""
        echo "=== Testing read performance ==="
        dd if=/data/perf-test.dat of=/dev/null bs=1M count=100 iflag=direct
        echo "Read test completed"
        echo ""
        echo "=== File listing ==="
        ls -lh /cephfs/
        echo ""
        echo "All tests completed!"
        sleep 3600
    volumeMounts:
    - name: cephfs-vol
      mountPath: /cephfs
  volumes:
  - name: cephfs-vol
    persistentVolumeClaim:
      claimName: cephfs-test-pvc
  restartPolicy: Never
---
# Test Pod for multiple concurrent access (CephFS)
apiVersion: v1
kind: Pod
metadata:
  name: cephfs-concurrent-test-pod-1
  namespace: rook-ceph
spec:
  containers:
  - name: tester
    image: 192.168.40.248/library/busybox:1.36.1-1
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "=== Concurrent Test Pod 1 ==="
        for i in $(seq 1 10); do
          echo "Write iteration $i from pod-1" >> /cephfs/concurrent-test.txt
          sleep 2
        done
        echo "=== Content from concurrent test file ==="
        cat /cephfs/concurrent-test.txt
        echo "Pod 1 test completed!"
        sleep 3600
    volumeMounts:
    - name: cephfs-vol
      mountPath: /cephfs
  volumes:
  - name: cephfs-vol
    persistentVolumeClaim:
      claimName: cephfs-test-pvc
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: cephfs-concurrent-test-pod-2
  namespace: rook-ceph
spec:
  containers:
  - name: tester
    image: 192.168.40.248/library/busybox:1.36.1-1
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "=== Concurrent Test Pod 2 ==="
        for i in $(seq 1 10); do
          echo "Write iteration $i from pod-2" >> /cephfs/concurrent-test.txt
          sleep 2
        done
        echo "=== Content from concurrent test file ==="
        cat /cephfs/concurrent-test.txt
        echo "Pod 2 test completed!"
        sleep 3600
    volumeMounts:
    - name: cephfs-vol
      mountPath: /cephfs
  volumes:
  - name: cephfs-vol
    persistentVolumeClaim:
      claimName: cephfs-test-pvc
  restartPolicy: Never
