apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-operator
  namespace: kubeflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-operator
rules:
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["sparkapplications", "sparkapplications/status", "sparkapplications/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["scheduledsparkapplications", "scheduledsparkapplications/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""],
  resources: ["configmaps", "serviceaccounts", "services", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"],
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"],
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"],
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""],
  resources: ["nodes", "events", "namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-operator
subjects:
- kind: ServiceAccount
  name: spark-operator
  namespace: kubeflow
roleRef:
  kind: ClusterRole
  name: spark-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-operator
  namespace: kubeflow
  labels:
    app: spark-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-operator
  template:
    metadata:
      labels:
        app: spark-operator
    spec:
      serviceAccountName: spark-operator
      containers:
      - name: spark-operator
        image: ghcr.io/kubeflow/spark-operator/controller:v2.4.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: webhook
        env:
        - name: WATCH_NAMESPACE
          value: "kubeflow"
        - name: SPARK_OPERATOR_WEBHOOK_PORT
          value: "8080"
        - name: LEADER_ELECTION_NAMESPACE
          value: "kubeflow"
        - name: SPARK_OPERATOR_NAMESPACE
          value: "kubeflow"
        - name: ENABLE_BATCH_SCHEDULER
          value: "false"
        - name: ENABLE_METRICS
          value: "true"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
