apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ${cluster_name}-blockpool
  namespace: ${namespace}
spec:
  failureDomain: host
  replicated:
    size: 3
    requireSafeReplicaSize: true
  parameters:
    "pg_autoscale_mode": "off"
    "pg_num": "128"
    "pgp_num": "128"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ${cluster_name}-blockstorage
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
  "clusterID": "${namespace}"
  "pool": "${cluster_name}-blockpool"
  "imageFormat": "2"
  "imageFeatures": "layering"
  "csi.storage.k8s.io/provisioner-secret-name": "rook-csi-rbd-provisioner"
  "csi.storage.k8s.io/provisioner-secret-namespace": "${namespace}"
  "csi.storage.k8s.io/controller-expand-secret-name": "rook-csi-rbd-provisioner"
  "csi.storage.k8s.io/controller-expand-secret-namespace": "${namespace}"
  "csi.storage.k8s.io/node-stage-secret-name": "rook-csi-rbd-node"
  "csi.storage.k8s.io/node-stage-secret-namespace": "${namespace}"
  "csi.storage.k8s.io/fstype": "ext4"
reclaimPolicy: Delete
allowVolumeExpansion: true
