apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: ${cluster_name}
  namespace: ${namespace}
spec:
  dataDirHostPath: /var/lib/rook
  cephVersion:
    image: "192.168.40.248/library/ceph/ceph:v19.2.3"
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
    - name: balancer
      enabled: true
  dashboard:
    enabled: true
    ssl: true
    port: 8443
  mon:
    count: ${monitor_count}
  network:
    provider: host
  placement:
    all:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      osdsPerDevice: "1"
    nodes:
%{ for node in node_list ~}
    - name: ${node.name}
      devices:
%{ for device in node.devices ~}
      - name: ${device.name}
%{ endfor ~}
      resources: {}
%{ endfor ~}
  resources:
    mgr:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 125m
        memory: 512Mi
    mon:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 125m
        memory: 512Mi
    osd:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 2Gi
    mds:
      limits:
        cpu: "3"
        memory: 8Gi
      requests:
        cpu: 500m
        memory: 512Mi
    rgw:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 512Mi
